# ; docker-compose for intersystems iris
version: '3.9'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 52773:52773
      - 1972
    volumes:
      - ./:/home/irisowner/dev


